#!/usr/bin/env python3
"""Generate data/maps/skirmish-01.fmap - "Serpentine Ford", 96x64, two players.

TICKET-P6-MAP-01, MAP redesign under ADR-013. This map replaces the old
"Spine": a straight vertical wall of blocked cells down the centre column with a
couple of gaps and otherwise open ground. A straight wall reads as an imposed
barrier and plays as a binary - passable at the gap or not, with no interior
terrain to fight over. This is its answer: a river that MEANDERS down the
theatre, crossed by three bridges, with ridges and ruins that break the open
field into approach lanes and give each base a defensible alcove.

Character: the river-crossing map. The Serpentine is the map's central question:
whoever holds two of its three fords chooses where the war happens. A safe
ferrite patch sits by each base so the early economy is stable; the larger
contested patch sits forward in the open, so expanding is a decision made under
fire rather than a formality.

The 180-degree rotation symmetry about the map centre is the fairness invariant
and it is proved in tools/mapgen.py, not trusted. Regenerate with:
    python3 tools/gen_skirmish_01.py data/maps/skirmish-01.fmap
"""
import math
import sys

sys.path.insert(0, __file__.rsplit('/', 1)[0])
from mapgen import Canvas, report

W, H = 96, 64
STARTS = {0: (9, 9), 1: (86, 54)}     # a 180-rotation pair about (47.5, 31.5)
MIDX = (W - 1) / 2                     # 47.5

c = Canvas(W, H, STARTS, apron=4)

# ---- The Serpentine: a winding north-south river. A sine centred on the map
# centre is rotation-symmetric by construction; mapgen closes it under rotation
# so integer rounding cannot bias one bank. Amplitude 8 gives a river that
# wanders x=40..56, clear of both corner bases; the width breathes 3..5 cells so
# it reads as water carved by water, not a ruled channel.
def centre(y):
    return MIDX + 8.0 * math.sin(2 * math.pi * (y - (H - 1) / 2) / 44.0)


def halfwidth(y):
    return 1.6 + 0.5 * math.cos(2 * math.pi * (y - (H - 1) / 2) / 22.0)


c.river(centre, halfwidth, vertical=True)

# ---- Three fords: north, centre, south. Three crossings on a 64-tall map is
# the tempo lever - enough routes that no single ford can be camped shut, few
# enough that holding two of them is a real positional lead. Each deck is four
# rows deep so an attack wave crosses in formation rather than single file.
c.bridges([(10, 14), (30, 34), (50, 54)])

# ---- Terrain. Hills give each base a back wall and carve the midfield into a
# main lane and a flank; ruins and fences litter the ground by the fords so a
# crossing is fought through cover, not over a billiard table. Everything is
# stamped as a rotation pair, so the description of player 0's ground below is
# also, rotated, player 1's.
# Base 0 alcove: an L of hills behind the top-left base, leaving the apron open
# and a clear lane down the western edge - defensible, not sealed.
c.stamp(15, 15, 10, 3, 'h')      # shoulder wall below base 0
c.stamp(24, 7, 3, 9, 'h')        # east cheek of the base, funnelling toward the north ford

# Midfield ridge spur: splits the western bank into a direct central lane and a
# wider southern flank, so a turtle on one ford can be gone round.
c.stamp(31, 33, 4, 10, 'h')      # western bank spur

# Ruins by the fords: cover on the approaches.
c.stamp(33, 20, 5, 4, 'r')       # ruins north-of-centre, west bank
c.stamp(20, 31, 5, 4, 'r')       # ruins on the central-lane approach

# Fence lines: light cover that shapes a fight without blocking a lane.
c.stamp(24, 24, 9, 2, 'f')
c.stamp(18, 49, 8, 2, 'f')

# ---- Ferrite: 20 cells = 240,000 credits, matching skirmish-02/03. Per player
# a safe 4-cell patch by the base and a larger 6-cell patch forward beside the
# central ford, in ground the enemy can reach. Rotation makes player 1's
# economy the mirror of player 0's.
SAFE = [(0, 0), (1, 0), (0, 1), (1, 1)]                       # 2x2, 4 cells
CONTEST = [(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1)]    # 3x2, 6 cells
c.cluster(17, 19, SAFE)          # safe patch, 13 cells from base 0
c.cluster(37, 28, CONTEST)       # contested patch beside the central ford

fields, blocked, density = c.validate(expected_fields=20, density_range=(0.08, 0.10))

path = sys.argv[1] if len(sys.argv) > 1 else "skirmish-01.fmap"
c.emit(path, [
    "# Serpentine Ford. The Serpentine river winds the length of the theatre and",
    "# is forded three times: north, centre and south. Hold two of the three and",
    "# you choose where the war happens. Generated by tools/gen_skirmish_01.py;",
    "# edit that script and regenerate rather than editing this file by hand - the",
    "# 180-degree rotation symmetry is the fairness invariant and it is checked",
    "# there (tools/mapgen.py).",
])
report("skirmish-01 (Serpentine Ford)", c, fields, blocked, density, path, "3 fords")
