#!/usr/bin/env python3
"""Generate data/maps/test-4seat.fmap - a FOUR-SEAT TEST FIXTURE, 96x96.

THIS IS NOT A SHIPPED SKIRMISH MAP AND MUST NEVER BE OFFERED AS ONE. It exists
so the runner's multiseatgate has a map that declares four starts, and it
carries NO FAIRNESS PROOF: it uses mapgen's asymmetric mode, so the 180-degree
rotation symmetry that every map in data/maps/skirmish-*.fmap is built on and
proved against does not apply and is not claimed. Four starts cannot be a
rotation pair, so the invariant is not merely unchecked here, it is not even
expressible. A four-player map that people are meant to play would need a
symmetry of order four and a proof to match, which is a design job (doc 26) and
not this file.

What it IS good for, and what the gate uses it for: four starts, one per corner
quadrant, far enough apart to be four separate bases, on open ground each can
walk out of. That is enough to prove the placement code seats four commanders,
that victory needs three of them gone rather than one, and that the AI does not
care which seat it is.

The starts are deliberately spread across the map's midline in BOTH directions,
two left of centre and two right of it, so the "lay the opening force out
towards the middle" rule in MapLoader.PlaceSkirmishStart is exercised in both of
its outcomes rather than only one.

Regenerate with:
    python3 tools/gen_testmap_4seat.py data/maps/test-4seat.fmap
"""
import sys

sys.path.insert(0, __file__.rsplit('/', 1)[0])
from mapgen import Canvas, report

W, H = 96, 96
# One start per quadrant. x=12 and x=83 straddle the vertical midline (48), so
# seats 0 and 2 lean their force right and seats 1 and 3 lean theirs left.
STARTS = {0: (12, 12), 1: (83, 12), 2: (12, 83), 3: (83, 83)}

c = Canvas(W, H, STARTS, apron=4, symmetric=False)

# ---- Terrain. A cross of ridges through the middle quarters, leaving every
# edge lane and the centre open: enough obstruction that the map is not a bare
# field and pathing is exercised, nowhere near enough to seal a quadrant off.
for (x, y, dx, dy, ch) in [
    (30, 20, 6, 14, 'h'), (60, 20, 6, 14, 'h'),
    (30, 62, 6, 14, 'h'), (60, 62, 6, 14, 'h'),
    (20, 44, 14, 6, 'r'), (62, 44, 14, 6, 'r'),
    (44, 20, 8, 5, 'f'), (44, 71, 8, 5, 'f'),
]:
    c.stamp(x, y, dx, dy, ch)

# ---- Ferrite. A patch beside each base so all four seats have an economy to
# start on, plus one contested block in the middle. Sixteen cells per seat's
# reach is not balanced and is not claimed to be; it is fuel for the harvesters
# the gate watches.
PATCH = [(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1)]
for (fx, fy) in [(20, 18), (73, 18), (20, 76), (73, 76), (45, 45)]:
    c.cluster(fx, fy, PATCH)

fields, blocked, density = c.validate(expected_fields=30, density_range=(0.04, 0.10))

path = sys.argv[1] if len(sys.argv) > 1 else "test-4seat.fmap"
c.emit(path, [
    "# TEST FIXTURE, NOT A PLAYABLE SKIRMISH MAP. Four starts, one per quadrant,",
    "# for the runner's multiseatgate. Asymmetric by construction, so it carries",
    "# NO fairness proof: the 180-degree rotation invariant every map in this",
    "# directory is built on cannot even be stated for four starts. Do not offer",
    "# it in the skirmish map list. Generated by tools/gen_testmap_4seat.py; edit",
    "# that script and regenerate rather than editing this file by hand.",
])
report("test-4seat (FOUR-SEAT TEST FIXTURE, not a shipped map)", c, fields, blocked, density, path,
       "none: every quadrant connects round the ridges")
